{"original_position": 82, "diff_hunk": "@@ -174,3 +183,61 @@ def country(self):\n     @cached_property\n     def request_time(self):\n         return self.request.received_at\n+\n+\n+class ApprovalRequest(models.Model):\n+    recipe = models.ForeignKey(Recipe, related_name='approval_requests')\n+    created = models.DateTimeField(default=datetime.now)\n+    creator = models.ForeignKey(User)\n+    active = models.BooleanField(default=True)\n+\n+    class IsNotActive(Exception):\n+        pass\n+\n+    @property\n+    def is_approved(self):\n+        return self.approval is not None\n+\n+    def approve(self, user):\n+        if self.active:\n+            approval = Approval(approval_request=self, creator=user)\n+            approval.save()\n+\n+            self.active = False\n+            self.save()\n+\n+            self.recipe.approval = approval\n+            self.recipe.save()\n+        else:\n+            raise self.IsNotActive('Approval request has already been closed.')", "body_text": "I really like this pattern of raising an exception from the class itself, it's neato!", "pull_request_url": "https://api.github.com/repos/mozilla/normandy/pulls/141", "url": "https://api.github.com/repos/mozilla/normandy/pulls/comments/62569717", "created_at": "2016-05-09T20:45:28Z", "author_association": "MEMBER", "body": "I really like this pattern of raising an exception from the class itself, it's neato!\n", "updated_at": "2016-05-18T23:24:11Z", "html_url": "https://github.com/mozilla/normandy/pull/141#discussion_r62569717", "pull_request_review_id": null, "_links": {"self": {"href": "https://api.github.com/repos/mozilla/normandy/pulls/comments/62569717"}, "html": {"href": "https://github.com/mozilla/normandy/pull/141#discussion_r62569717"}, "pull_request": {"href": "https://api.github.com/repos/mozilla/normandy/pulls/141"}}, "commit_id": "9976e74f22df740700d6c9a9d3a6ec3dff91e30e", "user": {"following_url": "https://api.github.com/users/Osmose/following{/other_user}", "events_url": "https://api.github.com/users/Osmose/events{/privacy}", "organizations_url": "https://api.github.com/users/Osmose/orgs", "url": "https://api.github.com/users/Osmose", "gists_url": "https://api.github.com/users/Osmose/gists{/gist_id}", "html_url": "https://github.com/Osmose", "subscriptions_url": "https://api.github.com/users/Osmose/subscriptions", "avatar_url": "https://avatars1.githubusercontent.com/u/193106?v=4", "repos_url": "https://api.github.com/users/Osmose/repos", "received_events_url": "https://api.github.com/users/Osmose/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/Osmose/starred{/owner}{/repo}", "site_admin": false, "login": "Osmose", "type": "User", "id": 193106, "followers_url": "https://api.github.com/users/Osmose/followers"}, "position": 142, "path": "normandy/recipes/models.py", "body_html": "<p>I really like this pattern of raising an exception from the class itself, it's neato!</p>", "original_commit_id": "f0ac4be801337ce783459d8455b1aa3f08980416", "id": 62569717}