{"body": "Well, the good news is that the build took 4 and a half hours and finished successfully.\r\n\r\nThe bad news is that it still failed trying to pull the artifact from the build task into the testing task:\r\n\r\n```\r\nDownloading build result\r\n\r\ngzip: stdin: unexpected end of file\r\ntar: Child returned status 1\r\ntar: Error is not recoverable: exiting now\r\n```\r\n\r\n@mythmon said that he asked the TaskCluster folks about this when we first saw it a few days ago and they said it was due to a deploy that day and had been resolved. That doesn't appear to be the case here.", "body_text": "Well, the good news is that the build took 4 and a half hours and finished successfully.\nThe bad news is that it still failed trying to pull the artifact from the build task into the testing task:\nDownloading build result\n\ngzip: stdin: unexpected end of file\ntar: Child returned status 1\ntar: Error is not recoverable: exiting now\n\n@mythmon said that he asked the TaskCluster folks about this when we first saw it a few days ago and they said it was due to a deploy that day and had been resolved. That doesn't appear to be the case here.", "url": "https://api.github.com/repos/mozilla/normandy/issues/comments/293767801", "created_at": "2017-04-13T03:17:44Z", "author_association": "MEMBER", "html_url": "https://github.com/mozilla/normandy/pull/683#issuecomment-293767801", "updated_at": "2017-04-13T03:17:44Z", "user": {"following_url": "https://api.github.com/users/Osmose/following{/other_user}", "events_url": "https://api.github.com/users/Osmose/events{/privacy}", "organizations_url": "https://api.github.com/users/Osmose/orgs", "url": "https://api.github.com/users/Osmose", "gists_url": "https://api.github.com/users/Osmose/gists{/gist_id}", "html_url": "https://github.com/Osmose", "subscriptions_url": "https://api.github.com/users/Osmose/subscriptions", "avatar_url": "https://avatars1.githubusercontent.com/u/193106?v=4", "repos_url": "https://api.github.com/users/Osmose/repos", "received_events_url": "https://api.github.com/users/Osmose/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/Osmose/starred{/owner}{/repo}", "site_admin": false, "login": "Osmose", "type": "User", "id": 193106, "followers_url": "https://api.github.com/users/Osmose/followers"}, "body_html": "<p>Well, the good news is that the build took 4 and a half hours and finished successfully.</p>\n<p>The bad news is that it still failed trying to pull the artifact from the build task into the testing task:</p>\n<pre><code>Downloading build result\n\ngzip: stdin: unexpected end of file\ntar: Child returned status 1\ntar: Error is not recoverable: exiting now\n</code></pre>\n<p><a class=\"user-mention\" href=\"https://github.com/mythmon\">@mythmon</a> said that he asked the TaskCluster folks about this when we first saw it a few days ago and they said it was due to a deploy that day and had been resolved. That doesn't appear to be the case here.</p>", "id": 293767801, "issue_url": "https://api.github.com/repos/mozilla/normandy/issues/683"}