{"original_position": 28, "diff_hunk": "@@ -12,6 +12,48 @@ add_task(withDriver(Assert, async function uuids(driver) {\n   isnot(uuid1, uuid2, \"uuids are unique\");\n }));\n \n+add_task(withDriver(Assert, async function installXpi(driver) {\n+  // Test that we can install an XPI from any URL\n+  const dir = getChromeDir(getResolvedURI(gTestPath));\n+  dir.append(\"fixtures\");\n+  dir.append(\"normandy.xpi\");\n+  const xpiUrl = Services.io.newFileURI(dir).spec;\n+  var addonId = await driver.installAddon(xpiUrl);\n+  is(addonId, \"normandydriver@example.com\", \"Expected test addon was installed\");\n+  isnot(addonId, null, \"Addon install was successful\");\n+\n+  // Installing kicks off an asychronous process which tries to read the manifest.json\n+  // to startup the addon. Note that onInstallEnded is triggered too early\n+  // which is why we need this delay.\n+  await new Promise(resolve => SimpleTest.executeSoon(resolve));\n+\n+  const uninstallMsg = await driver.uninstallAddon(addonId);\n+  is(uninstallMsg, null, `Uninstall returned an unexpected message [${uninstallMsg}]`);\n+}));\n+\n+add_task(withDriver(Assert, async function uninstallInvalidAddonId(driver) {\n+  // Test that we can install an XPI from any URL\n+  const invalidAddonId = \"not_a_valid_xpi_id@foo.bar\";\n+  try {\n+    await driver.uninstallAddon(invalidAddonId);\n+    ok(false, `Uninstall returned an unexpected null for success`);", "body_text": "It would be helpful if this failure message more explicitly indicated why we expected failure, rather than just that we didn't expect success...", "pull_request_url": "https://api.github.com/repos/mozilla/normandy/pulls/778", "url": "https://api.github.com/repos/mozilla/normandy/pulls/comments/122076443", "created_at": "2017-06-14T22:03:38Z", "author_association": "CONTRIBUTOR", "body": "It would be helpful if this failure message more explicitly indicated why we expected failure, rather than just that we didn't expect success...", "updated_at": "2017-06-15T19:56:17Z", "html_url": "https://github.com/mozilla/normandy/pull/778#discussion_r122076443", "pull_request_review_id": 44160378, "_links": {"self": {"href": "https://api.github.com/repos/mozilla/normandy/pulls/comments/122076443"}, "html": {"href": "https://github.com/mozilla/normandy/pull/778#discussion_r122076443"}, "pull_request": {"href": "https://api.github.com/repos/mozilla/normandy/pulls/778"}}, "commit_id": "dbb2b5aba2dd9803c76a77a0dae01a837d9bd9fe", "user": {"following_url": "https://api.github.com/users/gijsk/following{/other_user}", "events_url": "https://api.github.com/users/gijsk/events{/privacy}", "organizations_url": "https://api.github.com/users/gijsk/orgs", "url": "https://api.github.com/users/gijsk", "gists_url": "https://api.github.com/users/gijsk/gists{/gist_id}", "html_url": "https://github.com/gijsk", "subscriptions_url": "https://api.github.com/users/gijsk/subscriptions", "avatar_url": "https://avatars3.githubusercontent.com/u/375983?v=4", "repos_url": "https://api.github.com/users/gijsk/repos", "received_events_url": "https://api.github.com/users/gijsk/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/gijsk/starred{/owner}{/repo}", "site_admin": false, "login": "gijsk", "type": "User", "id": 375983, "followers_url": "https://api.github.com/users/gijsk/followers"}, "position": null, "path": "recipe-client-addon/test/browser/browser_NormandyDriver.js", "body_html": "<p>It would be helpful if this failure message more explicitly indicated why we expected failure, rather than just that we didn't expect success...</p>", "original_commit_id": "86326dfb8d17e7997d98aeaa9b2869634746dfaf", "id": 122076443}