{"body": "Writing a test for this feature is a little challenging because there is no specific \"problematic string\" that will reliably cause `validate()` to throw an exception (and indeed, any that we find should be reported as bugs to upstream, along the lines of https://github.com/Osmose/pyjexl/pull/12). I've instead written a test that mocks the JEXL parser to throw an exception, which seems like the cleanest way to test the behavior of our serializer in the case that the JEXL parser throws an exception.", "body_text": "Writing a test for this feature is a little challenging because there is no specific \"problematic string\" that will reliably cause validate() to throw an exception (and indeed, any that we find should be reported as bugs to upstream, along the lines of Osmose/pyjexl#12). I've instead written a test that mocks the JEXL parser to throw an exception, which seems like the cleanest way to test the behavior of our serializer in the case that the JEXL parser throws an exception.", "url": "https://api.github.com/repos/mozilla/normandy/issues/comments/373138395", "created_at": "2018-03-14T19:01:17Z", "author_association": "CONTRIBUTOR", "html_url": "https://github.com/mozilla/normandy/pull/1207#issuecomment-373138395", "updated_at": "2018-03-14T19:01:17Z", "user": {"following_url": "https://api.github.com/users/glasserc/following{/other_user}", "events_url": "https://api.github.com/users/glasserc/events{/privacy}", "organizations_url": "https://api.github.com/users/glasserc/orgs", "url": "https://api.github.com/users/glasserc", "gists_url": "https://api.github.com/users/glasserc/gists{/gist_id}", "html_url": "https://github.com/glasserc", "subscriptions_url": "https://api.github.com/users/glasserc/subscriptions", "avatar_url": "https://avatars0.githubusercontent.com/u/17006?v=4", "repos_url": "https://api.github.com/users/glasserc/repos", "received_events_url": "https://api.github.com/users/glasserc/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/glasserc/starred{/owner}{/repo}", "site_admin": false, "login": "glasserc", "type": "User", "id": 17006, "followers_url": "https://api.github.com/users/glasserc/followers"}, "body_html": "<p>Writing a test for this feature is a little challenging because there is no specific \"problematic string\" that will reliably cause <code>validate()</code> to throw an exception (and indeed, any that we find should be reported as bugs to upstream, along the lines of <a class=\"issue-link js-issue-link\" data-error-text=\"Failed to load issue title\" data-id=\"304497584\" data-permission-text=\"Issue title is private\" data-url=\"https://github.com/Osmose/pyjexl/issues/12\" href=\"https://github.com/Osmose/pyjexl/pull/12\">Osmose/pyjexl#12</a>). I've instead written a test that mocks the JEXL parser to throw an exception, which seems like the cleanest way to test the behavior of our serializer in the case that the JEXL parser throws an exception.</p>", "id": 373138395, "issue_url": "https://api.github.com/repos/mozilla/normandy/issues/1207"}