{"body_text": "This has come up in CI. @Osmose said that path.replaceWith() is a Babel thing. I bet this has something to do with unpinned Node dependencies, and possibly Babili.\nTraceback:\nwebpack_loader.exceptions.WebpackError:              Error in              unknown: Don't use `path.replaceWith()` with a source string, use `path.replaceWithSourceString()`\nself = <test_views.TestSelfRepair object at 0x7fb69d6e6a58>\nclient = <django.test.client.Client object at 0x7fb69d6ef908>\n\n    @pytest.mark.django_db\n    def test_doesnt_redirect(self, client):\n>       assert client.get(self.url).status_code == 200\n\nnormandy/selfrepair/tests/test_views.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/usr/local/lib/python3.6/site-packages/django/test/client.py:529: in get\n    **extra)\n/usr/local/lib/python3.6/site-packages/django/test/client.py:333: in get\n    return self.generic('GET', path, secure=secure, **r)\n/usr/local/lib/python3.6/site-packages/django/test/client.py:409: in generic\n    return self.request(**r)\n/usr/local/lib/python3.6/site-packages/django/test/client.py:494: in request\n    six.reraise(*exc_info)\n/usr/local/lib/python3.6/site-packages/django/utils/six.py:686: in reraise\n    raise value\n/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py:42: in inner\n    response = get_response(request)\n/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py:187: in _get_response\n    response = self.process_exception_by_middleware(e, request)\n/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py:185: in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\nnormandy/base/decorators.py:17: in wrapped_view\n    return view_func(*args, **kwargs)\n/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py:43: in _cache_controlled\n    response = viewfunc(request, *args, **kw)\nnormandy/selfrepair/views.py:19: in repair\n    'classify_client_url': classify_client_url,\n/usr/local/lib/python3.6/site-packages/django/shortcuts.py:30: in render\n    content = loader.render_to_string(template_name, context, request, using=using)\n/usr/local/lib/python3.6/site-packages/django/template/loader.py:68: in render_to_string\n    return template.render(context, request)\n/usr/local/lib/python3.6/site-packages/django/template/backends/django.py:66: in render\n    return self.template.render(context)\n/usr/local/lib/python3.6/site-packages/django/template/base.py:208: in render\n    return self._render(context)\n/usr/local/lib/python3.6/site-packages/django/test/utils.py:94: in instrumented_test_render\n    return self.nodelist.render(context)\n/usr/local/lib/python3.6/site-packages/django/template/base.py:994: in render\n    bit = node.render_annotated(context)\n/usr/local/lib/python3.6/site-packages/django/template/base.py:961: in render_annotated\n    return self.render(context)\n/usr/local/lib/python3.6/site-packages/django/template/library.py:203: in render\n    output = self.func(*resolved_args, **resolved_kwargs)\nnormandy/base/templatetags/normandy_webpack_loader.py:19: in render_bundle\n    chunks = get_files(bundle_name, extension=extension, config=config)\n/usr/local/lib/python3.6/site-packages/webpack_loader/templatetags/webpack_loader.py:67: in get_files\n    return list(_get_bundle(bundle_name, extension, config))\n/usr/local/lib/python3.6/site-packages/webpack_loader/templatetags/webpack_loader.py:32: in _get_bundle\n    bundle = get_loader(config).get_bundle(bundle_name)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <webpack_loader.loader.WebpackLoader object at 0x7fb69e0c6e10>\nbundle_name = 'selfrepair'\n\n    def get_bundle(self, bundle_name):\n        assets = self.get_assets()\n    \n        if settings.DEBUG:\n            # poll when debugging and block request until bundle is compiled\n            # TODO: support timeouts\n            while assets['status'] == 'compiling':\n                time.sleep(self.config['POLL_INTERVAL'])\n                assets = self.get_assets()\n    \n        if assets.get('status') == 'done':\n            chunks = assets['chunks'][bundle_name]\n            return self.filter_chunks(chunks)\n    \n        elif assets.get('status') == 'error':\n            if 'file' not in assets:\n                assets['file'] = ''\n            error = u\"\"\"\n                {error} in {file}\n                {message}\n                \"\"\".format(**assets)\n>           raise WebpackError(error)\nE           webpack_loader.exceptions.WebpackError: \nE                       Error in \nE                       unknown: Don't use `path.replaceWith()` with a source string, use `path.replaceWithSourceString()`\n\n/usr/local/lib/python3.6/site-packages/webpack_loader/loader.py:74: WebpackError", "labels": [{"url": "https://api.github.com/repos/mozilla/normandy/labels/bug", "color": "b60205", "default": true, "id": 482996638, "name": "bug"}], "number": 812, "assignee": {"following_url": "https://api.github.com/users/Osmose/following{/other_user}", "events_url": "https://api.github.com/users/Osmose/events{/privacy}", "organizations_url": "https://api.github.com/users/Osmose/orgs", "url": "https://api.github.com/users/Osmose", "gists_url": "https://api.github.com/users/Osmose/gists{/gist_id}", "html_url": "https://github.com/Osmose", "subscriptions_url": "https://api.github.com/users/Osmose/subscriptions", "avatar_url": "https://avatars1.githubusercontent.com/u/193106?v=4", "repos_url": "https://api.github.com/users/Osmose/repos", "received_events_url": "https://api.github.com/users/Osmose/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/Osmose/starred{/owner}{/repo}", "site_admin": false, "login": "Osmose", "type": "User", "id": 193106, "followers_url": "https://api.github.com/users/Osmose/followers"}, "repository_url": "https://api.github.com/repos/mozilla/normandy", "closed_at": "2017-06-14T22:05:09Z", "body_html": "<p>This has come up in CI. <a class=\"user-mention\" href=\"https://github.com/osmose\">@Osmose</a> said that <code>path.replaceWith()</code> is a Babel thing. I bet this has something to do with unpinned Node dependencies, and possibly Babili.</p>\n<p>Traceback:</p>\n<pre><code>webpack_loader.exceptions.WebpackError:              Error in              unknown: Don't use `path.replaceWith()` with a source string, use `path.replaceWithSourceString()`\nself = &lt;test_views.TestSelfRepair object at 0x7fb69d6e6a58&gt;\nclient = &lt;django.test.client.Client object at 0x7fb69d6ef908&gt;\n\n    @pytest.mark.django_db\n    def test_doesnt_redirect(self, client):\n&gt;       assert client.get(self.url).status_code == 200\n\nnormandy/selfrepair/tests/test_views.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/usr/local/lib/python3.6/site-packages/django/test/client.py:529: in get\n    **extra)\n/usr/local/lib/python3.6/site-packages/django/test/client.py:333: in get\n    return self.generic('GET', path, secure=secure, **r)\n/usr/local/lib/python3.6/site-packages/django/test/client.py:409: in generic\n    return self.request(**r)\n/usr/local/lib/python3.6/site-packages/django/test/client.py:494: in request\n    six.reraise(*exc_info)\n/usr/local/lib/python3.6/site-packages/django/utils/six.py:686: in reraise\n    raise value\n/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py:42: in inner\n    response = get_response(request)\n/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py:187: in _get_response\n    response = self.process_exception_by_middleware(e, request)\n/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py:185: in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\nnormandy/base/decorators.py:17: in wrapped_view\n    return view_func(*args, **kwargs)\n/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py:43: in _cache_controlled\n    response = viewfunc(request, *args, **kw)\nnormandy/selfrepair/views.py:19: in repair\n    'classify_client_url': classify_client_url,\n/usr/local/lib/python3.6/site-packages/django/shortcuts.py:30: in render\n    content = loader.render_to_string(template_name, context, request, using=using)\n/usr/local/lib/python3.6/site-packages/django/template/loader.py:68: in render_to_string\n    return template.render(context, request)\n/usr/local/lib/python3.6/site-packages/django/template/backends/django.py:66: in render\n    return self.template.render(context)\n/usr/local/lib/python3.6/site-packages/django/template/base.py:208: in render\n    return self._render(context)\n/usr/local/lib/python3.6/site-packages/django/test/utils.py:94: in instrumented_test_render\n    return self.nodelist.render(context)\n/usr/local/lib/python3.6/site-packages/django/template/base.py:994: in render\n    bit = node.render_annotated(context)\n/usr/local/lib/python3.6/site-packages/django/template/base.py:961: in render_annotated\n    return self.render(context)\n/usr/local/lib/python3.6/site-packages/django/template/library.py:203: in render\n    output = self.func(*resolved_args, **resolved_kwargs)\nnormandy/base/templatetags/normandy_webpack_loader.py:19: in render_bundle\n    chunks = get_files(bundle_name, extension=extension, config=config)\n/usr/local/lib/python3.6/site-packages/webpack_loader/templatetags/webpack_loader.py:67: in get_files\n    return list(_get_bundle(bundle_name, extension, config))\n/usr/local/lib/python3.6/site-packages/webpack_loader/templatetags/webpack_loader.py:32: in _get_bundle\n    bundle = get_loader(config).get_bundle(bundle_name)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = &lt;webpack_loader.loader.WebpackLoader object at 0x7fb69e0c6e10&gt;\nbundle_name = 'selfrepair'\n\n    def get_bundle(self, bundle_name):\n        assets = self.get_assets()\n    \n        if settings.DEBUG:\n            # poll when debugging and block request until bundle is compiled\n            # TODO: support timeouts\n            while assets['status'] == 'compiling':\n                time.sleep(self.config['POLL_INTERVAL'])\n                assets = self.get_assets()\n    \n        if assets.get('status') == 'done':\n            chunks = assets['chunks'][bundle_name]\n            return self.filter_chunks(chunks)\n    \n        elif assets.get('status') == 'error':\n            if 'file' not in assets:\n                assets['file'] = ''\n            error = u\"\"\"\n                {error} in {file}\n                {message}\n                \"\"\".format(**assets)\n&gt;           raise WebpackError(error)\nE           webpack_loader.exceptions.WebpackError: \nE                       Error in \nE                       unknown: Don't use `path.replaceWith()` with a source string, use `path.replaceWithSourceString()`\n\n/usr/local/lib/python3.6/site-packages/webpack_loader/loader.py:74: WebpackError\n</code></pre>", "id": 235720673, "title": "Traceback: Don't use `path.replaceWith()` with a source string", "comments": 2, "state": "closed", "body": "This has come up in CI. @Osmose said that `path.replaceWith()` is a Babel thing. I bet this has something to do with unpinned Node dependencies, and possibly Babili.\r\n\r\nTraceback:\r\n\r\n```\r\nwebpack_loader.exceptions.WebpackError:              Error in              unknown: Don't use `path.replaceWith()` with a source string, use `path.replaceWithSourceString()`\r\nself = <test_views.TestSelfRepair object at 0x7fb69d6e6a58>\r\nclient = <django.test.client.Client object at 0x7fb69d6ef908>\r\n\r\n    @pytest.mark.django_db\r\n    def test_doesnt_redirect(self, client):\r\n>       assert client.get(self.url).status_code == 200\r\n\r\nnormandy/selfrepair/tests/test_views.py:28: \r\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \r\n/usr/local/lib/python3.6/site-packages/django/test/client.py:529: in get\r\n    **extra)\r\n/usr/local/lib/python3.6/site-packages/django/test/client.py:333: in get\r\n    return self.generic('GET', path, secure=secure, **r)\r\n/usr/local/lib/python3.6/site-packages/django/test/client.py:409: in generic\r\n    return self.request(**r)\r\n/usr/local/lib/python3.6/site-packages/django/test/client.py:494: in request\r\n    six.reraise(*exc_info)\r\n/usr/local/lib/python3.6/site-packages/django/utils/six.py:686: in reraise\r\n    raise value\r\n/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py:42: in inner\r\n    response = get_response(request)\r\n/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py:187: in _get_response\r\n    response = self.process_exception_by_middleware(e, request)\r\n/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py:185: in _get_response\r\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\r\nnormandy/base/decorators.py:17: in wrapped_view\r\n    return view_func(*args, **kwargs)\r\n/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py:43: in _cache_controlled\r\n    response = viewfunc(request, *args, **kw)\r\nnormandy/selfrepair/views.py:19: in repair\r\n    'classify_client_url': classify_client_url,\r\n/usr/local/lib/python3.6/site-packages/django/shortcuts.py:30: in render\r\n    content = loader.render_to_string(template_name, context, request, using=using)\r\n/usr/local/lib/python3.6/site-packages/django/template/loader.py:68: in render_to_string\r\n    return template.render(context, request)\r\n/usr/local/lib/python3.6/site-packages/django/template/backends/django.py:66: in render\r\n    return self.template.render(context)\r\n/usr/local/lib/python3.6/site-packages/django/template/base.py:208: in render\r\n    return self._render(context)\r\n/usr/local/lib/python3.6/site-packages/django/test/utils.py:94: in instrumented_test_render\r\n    return self.nodelist.render(context)\r\n/usr/local/lib/python3.6/site-packages/django/template/base.py:994: in render\r\n    bit = node.render_annotated(context)\r\n/usr/local/lib/python3.6/site-packages/django/template/base.py:961: in render_annotated\r\n    return self.render(context)\r\n/usr/local/lib/python3.6/site-packages/django/template/library.py:203: in render\r\n    output = self.func(*resolved_args, **resolved_kwargs)\r\nnormandy/base/templatetags/normandy_webpack_loader.py:19: in render_bundle\r\n    chunks = get_files(bundle_name, extension=extension, config=config)\r\n/usr/local/lib/python3.6/site-packages/webpack_loader/templatetags/webpack_loader.py:67: in get_files\r\n    return list(_get_bundle(bundle_name, extension, config))\r\n/usr/local/lib/python3.6/site-packages/webpack_loader/templatetags/webpack_loader.py:32: in _get_bundle\r\n    bundle = get_loader(config).get_bundle(bundle_name)\r\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \r\n\r\nself = <webpack_loader.loader.WebpackLoader object at 0x7fb69e0c6e10>\r\nbundle_name = 'selfrepair'\r\n\r\n    def get_bundle(self, bundle_name):\r\n        assets = self.get_assets()\r\n    \r\n        if settings.DEBUG:\r\n            # poll when debugging and block request until bundle is compiled\r\n            # TODO: support timeouts\r\n            while assets['status'] == 'compiling':\r\n                time.sleep(self.config['POLL_INTERVAL'])\r\n                assets = self.get_assets()\r\n    \r\n        if assets.get('status') == 'done':\r\n            chunks = assets['chunks'][bundle_name]\r\n            return self.filter_chunks(chunks)\r\n    \r\n        elif assets.get('status') == 'error':\r\n            if 'file' not in assets:\r\n                assets['file'] = ''\r\n            error = u\"\"\"\r\n                {error} in {file}\r\n                {message}\r\n                \"\"\".format(**assets)\r\n>           raise WebpackError(error)\r\nE           webpack_loader.exceptions.WebpackError: \r\nE                       Error in \r\nE                       unknown: Don't use `path.replaceWith()` with a source string, use `path.replaceWithSourceString()`\r\n\r\n/usr/local/lib/python3.6/site-packages/webpack_loader/loader.py:74: WebpackError\r\n```", "events_url": "https://api.github.com/repos/mozilla/normandy/issues/812/events", "labels_url": "https://api.github.com/repos/mozilla/normandy/issues/812/labels{/name}", "author_association": "MEMBER", "comments_url": "https://api.github.com/repos/mozilla/normandy/issues/812/comments", "html_url": "https://github.com/mozilla/normandy/issues/812", "updated_at": "2017-06-14T22:05:09Z", "user": {"following_url": "https://api.github.com/users/mythmon/following{/other_user}", "events_url": "https://api.github.com/users/mythmon/events{/privacy}", "organizations_url": "https://api.github.com/users/mythmon/orgs", "url": "https://api.github.com/users/mythmon", "gists_url": "https://api.github.com/users/mythmon/gists{/gist_id}", "html_url": "https://github.com/mythmon", "subscriptions_url": "https://api.github.com/users/mythmon/subscriptions", "avatar_url": "https://avatars3.githubusercontent.com/u/305049?v=4", "repos_url": "https://api.github.com/users/mythmon/repos", "received_events_url": "https://api.github.com/users/mythmon/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/mythmon/starred{/owner}{/repo}", "site_admin": false, "login": "mythmon", "type": "User", "id": 305049, "followers_url": "https://api.github.com/users/mythmon/followers"}, "milestone": null, "locked": false, "url": "https://api.github.com/repos/mozilla/normandy/issues/812", "created_at": "2017-06-13T23:23:45Z", "assignees": [{"following_url": "https://api.github.com/users/Osmose/following{/other_user}", "events_url": "https://api.github.com/users/Osmose/events{/privacy}", "organizations_url": "https://api.github.com/users/Osmose/orgs", "url": "https://api.github.com/users/Osmose", "gists_url": "https://api.github.com/users/Osmose/gists{/gist_id}", "html_url": "https://github.com/Osmose", "subscriptions_url": "https://api.github.com/users/Osmose/subscriptions", "avatar_url": "https://avatars1.githubusercontent.com/u/193106?v=4", "repos_url": "https://api.github.com/users/Osmose/repos", "received_events_url": "https://api.github.com/users/Osmose/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/Osmose/starred{/owner}{/repo}", "site_admin": false, "login": "Osmose", "type": "User", "id": 193106, "followers_url": "https://api.github.com/users/Osmose/followers"}]}