{"body": "Hmmm. I _was_ getting the error locally, but the last commit fixes it for me. Yet CI is still having issues.\r\n\r\nWe might have to make a wait-for-postgres script or something.", "body_text": "Hmmm. I was getting the error locally, but the last commit fixes it for me. Yet CI is still having issues.\nWe might have to make a wait-for-postgres script or something.", "url": "https://api.github.com/repos/mozilla/normandy/issues/comments/274248056", "created_at": "2017-01-21T08:21:14Z", "author_association": "MEMBER", "html_url": "https://github.com/mozilla/normandy/pull/440#issuecomment-274248056", "updated_at": "2017-01-21T08:21:14Z", "user": {"following_url": "https://api.github.com/users/Osmose/following{/other_user}", "events_url": "https://api.github.com/users/Osmose/events{/privacy}", "organizations_url": "https://api.github.com/users/Osmose/orgs", "url": "https://api.github.com/users/Osmose", "gists_url": "https://api.github.com/users/Osmose/gists{/gist_id}", "html_url": "https://github.com/Osmose", "subscriptions_url": "https://api.github.com/users/Osmose/subscriptions", "avatar_url": "https://avatars1.githubusercontent.com/u/193106?v=4", "repos_url": "https://api.github.com/users/Osmose/repos", "received_events_url": "https://api.github.com/users/Osmose/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/Osmose/starred{/owner}{/repo}", "site_admin": false, "login": "Osmose", "type": "User", "id": 193106, "followers_url": "https://api.github.com/users/Osmose/followers"}, "body_html": "<p>Hmmm. I <em>was</em> getting the error locally, but the last commit fixes it for me. Yet CI is still having issues.</p>\n<p>We might have to make a wait-for-postgres script or something.</p>", "id": 274248056, "issue_url": "https://api.github.com/repos/mozilla/normandy/issues/440"}