{"body": "Circle failures are related. I think the Python tests failed because the template was updated without updating one of the tests that rely on them.", "body_text": "Circle failures are related. I think the Python tests failed because the template was updated without updating one of the tests that rely on them.", "url": "https://api.github.com/repos/mozilla/normandy/issues/comments/331939587", "created_at": "2017-09-25T16:38:36Z", "author_association": "MEMBER", "html_url": "https://github.com/mozilla/normandy/pull/1038#issuecomment-331939587", "updated_at": "2017-09-25T16:38:36Z", "user": {"following_url": "https://api.github.com/users/mythmon/following{/other_user}", "events_url": "https://api.github.com/users/mythmon/events{/privacy}", "organizations_url": "https://api.github.com/users/mythmon/orgs", "url": "https://api.github.com/users/mythmon", "gists_url": "https://api.github.com/users/mythmon/gists{/gist_id}", "html_url": "https://github.com/mythmon", "subscriptions_url": "https://api.github.com/users/mythmon/subscriptions", "avatar_url": "https://avatars3.githubusercontent.com/u/305049?v=4", "repos_url": "https://api.github.com/users/mythmon/repos", "received_events_url": "https://api.github.com/users/mythmon/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/mythmon/starred{/owner}{/repo}", "site_admin": false, "login": "mythmon", "type": "User", "id": 305049, "followers_url": "https://api.github.com/users/mythmon/followers"}, "body_html": "<p>Circle failures are related. I think the Python tests failed because the template was updated without updating one of the tests that rely on them.</p>", "id": 331939587, "issue_url": "https://api.github.com/repos/mozilla/normandy/issues/1038"}