{"original_position": 31, "diff_hunk": "@@ -0,0 +1,129 @@\n+import appReducer from 'control/reducers';\n+import * as actions from 'control/actions/ColumnActions';\n+\n+import {\n+  initialState,\n+} from 'control/tests/fixtures';\n+\n+/**\n+ * Utility function to clone the initialState column array and its values\n+ * (This prevents nested objects from being cloned by reference)\n+ *\n+ * @return {Array} New array with cloned initialState values\n+ */\n+const cloneInitialArray = () => JSON.parse(JSON.stringify(initialState.columns));\n+\n+\n+/**\n+ * Utility function to get the index of a column\n+ * which is NOT shown by default.\n+ *\n+ * @return {Number} Index of non-default column to test against.\n+ */\n+const getNondefaultColumn = () => {\n+  let foundIndex;\n+  initialState.columns\n+    .find((col, index) => {\n+      foundIndex = index;\n+      return !col.enabled;\n+    });\n+\n+  if (!foundIndex) {", "body_text": "Should this compare specifically to undefined, since 0 is a valid value? Also, should this be an exception instead of just printing a warning? Test code probably shouldn't be tolerant of weird cases.", "pull_request_url": "https://api.github.com/repos/mozilla/normandy/pulls/388", "url": "https://api.github.com/repos/mozilla/normandy/pulls/comments/92691924", "created_at": "2016-12-15T20:19:25Z", "author_association": "MEMBER", "body": "Should this compare specifically to undefined, since `0` is a valid value? Also, should this be an exception instead of just printing a warning? Test code probably shouldn't be tolerant of weird cases.", "updated_at": "2016-12-19T16:56:33Z", "html_url": "https://github.com/mozilla/normandy/pull/388#discussion_r92691924", "pull_request_review_id": 13201086, "_links": {"self": {"href": "https://api.github.com/repos/mozilla/normandy/pulls/comments/92691924"}, "html": {"href": "https://github.com/mozilla/normandy/pull/388#discussion_r92691924"}, "pull_request": {"href": "https://api.github.com/repos/mozilla/normandy/pulls/388"}}, "commit_id": "cb5179088a80658131dc4bf3ffbecebf8f8a82bb", "user": {"following_url": "https://api.github.com/users/mythmon/following{/other_user}", "events_url": "https://api.github.com/users/mythmon/events{/privacy}", "organizations_url": "https://api.github.com/users/mythmon/orgs", "url": "https://api.github.com/users/mythmon", "gists_url": "https://api.github.com/users/mythmon/gists{/gist_id}", "html_url": "https://github.com/mythmon", "subscriptions_url": "https://api.github.com/users/mythmon/subscriptions", "avatar_url": "https://avatars3.githubusercontent.com/u/305049?v=4", "repos_url": "https://api.github.com/users/mythmon/repos", "received_events_url": "https://api.github.com/users/mythmon/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/mythmon/starred{/owner}{/repo}", "site_admin": false, "login": "mythmon", "type": "User", "id": 305049, "followers_url": "https://api.github.com/users/mythmon/followers"}, "position": null, "path": "client/control/tests/reducers/test_columnReducer.js", "body_html": "<p>Should this compare specifically to undefined, since <code>0</code> is a valid value? Also, should this be an exception instead of just printing a warning? Test code probably shouldn't be tolerant of weird cases.</p>", "original_commit_id": "400d6c64e149a38d454dab8e57706d99b11f625f", "id": 92691924}